user:
  data:
    initialize: true

spring:
  thymeleaf:
    cache: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        #show_sql: true
        #format_sql: true
        #use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.springframework:
    web: debug
    security: error
