user:
  data:
    initialize: true

spring:
  thymeleaf:
    cache: false
  jpa:
    properties:
      hibernate:
        #show_sql: true
        #format_sql: true
        #use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.springframework:
    web: debug
    security: DEBUG
